baseURL = 'https://xuelitian.github.io/'
languageCode = 'en-us'
title = 'Full Stack Data Engineer'
theme = 'paper'
enableRobotsTXT = true

[params]
  # header social icons
  github = 'xuelitian'
  linkedin = 'xuelitian'
  rss = true

  # home page profile
  avatar = 'https://avatars.githubusercontent.com/u/1487387'
  name = 'Kevin Tian'
  bio = 'Data & AI Architect'

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2